server:
  port: 8101

spring:
  application:
    name: DASH-Auth
    dynamic:
      p6spy: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    host: 192.168.1.213
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/dash_sys?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

  boot:
    admin:
      client:
        url: http://localhost:8401

  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 192.168.1.213
    port: 5672
    username: dash
    password: dash

info:
  app:
    name: ${spring.application.name}
    description: "DASH-Auth jwt认证"
    version: "0.0.1-SNAPSHOT"

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      #      defaultZone: http://dash:123456@localhost:8001/register/eureka/
      defaultZone: http://localhost:8001/register/eureka/

mybatis-plus:
  type-aliases-package: com.sprint.dash.entities.auth
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
